apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flaskapp
      annotations:
        kubectl.kubernetes.io/restartedAt: "2024-12-10T00:08:35Z" # If needed
    spec:
      containers:
        - name: flaskapp
          image: us-central1-docker.pkg.dev/stock-prediction-444218/us/flaskapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
